postsubmits:
  ppc64le-cloud/test-infra:
    - name: postsubmit-podutilities-job
      # Usage of this job is deprecated as we started using upstream images
      # Refer https://github.com/ppc64le-cloud/test-infra/blob/master/README.md#Deprecated
      labels:
        preset-image-builder: "true"
      decorate: true
      run_if_changed: 'images/pod-utilities'
      branches:
        - master
      extra_refs:
        - base_ref: v0.1.2
          org: vmware-tanzu
          repo: buildkit-cli-for-kubectl
      spec:
        serviceAccountName: build-img
        containers:
          - image: quay.io/powercloud/all-in-one:0.7
            command:
              - /bin/bash
            args:
              - -c
              - |
                set -o errexit
                set -o nounset
                set -o pipefail
                pushd $GOPATH/src/github.com/vmware-tanzu/buildkit-cli-for-kubectl
                make build install
                popd
                ca=$(base64 -w 0 /run/secrets/kubernetes.io/serviceaccount/ca.crt)
                token=$(cat /run/secrets/kubernetes.io/serviceaccount/token)
                namespace=$(cat /run/secrets/kubernetes.io/serviceaccount/namespace)
                cat >kubeconfig <<EOL
                apiVersion: v1
                kind: Config
                clusters:
                - name: default-cluster
                  cluster:
                    certificate-authority-data: ${ca}
                    server: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT_HTTPS}
                contexts:
                - name: default-context
                  context:
                    cluster: default-cluster
                    namespace: ${namespace}
                    user: default-user
                current-context: default-context
                users:
                - name: default-user
                  user:
                    token: ${token}
                EOL
                export KUBECONFIG=$(pwd)/kubeconfig
                export utils=(clonerefs entrypoint initupload sidecar)
                pushd images/pod-utilities
                export version=`cat version.txt`
                for i in ${utils[@]}
                do
                    sed "s/POD_UTILITY/$i/g" Dockerfile > Dockerfile_tmp
                    kubectl build --push --registry-secret quay-powercloud-regcred --namespace image-builder -t quay.io/powercloud/$i:amd64-$version -f Dockerfile_tmp ./
                    kubectl build --push --registry-secret quay-powercloud-regcred --kubeconfig /etc/kubeconfig/config --namespace image-builder -t quay.io/powercloud/$i:ppc64le-$version -f Dockerfile_tmp ./

                done
                popd
                curl -L https://github.com/estesp/manifest-tool/releases/download/v1.0.3/manifest-tool-linux-`go env GOARCH` -o /usr/local/bin/manifest-tool
                chmod +x /usr/local/bin/manifest-tool
                cat > config.json << EOL
                $DOCKER_CONFIG
                EOL
                for i in ${utils[@]}
                do
                cat > registry.yaml <<EOL
                image: quay.io/powercloud/$i:$version
                manifests:
                  -
                    image: quay.io/powercloud/$i:ppc64le-$version
                    platform:
                      architecture: ppc64le
                      os: linux
                  -
                    image: quay.io/powercloud/$i:amd64-$version
                    platform:
                      architecture: amd64
                      os: linux
                EOL
                manifest-tool --debug --docker-cfg `pwd` push from-spec registry.yaml
                done
