presubmits:
  ppc64le-cloud/pvsadm:
    - name: pull-pvsadm-verify-all
      decorate: true
      spec:
        containers:
          - image: golang:1.15
            command:
              - sh
            args:
              - -c
              - |
                set -o errexit
                go get -u github.com/google/addlicense
                ./hack/verify-all.sh
