presubmits:
  ocp-power-automation/ocp4-upi-powervs:
    - name: pull-ocp4-upi-powervs-terraform-validate
      always_run: true
      decorate: true
      spec:
        containers:
          - image: hashicorp/terraform
            command:
              - sh
            args:
              - -c
              - |
                set -o errexit
                terraform init
                terraform validate
      annotations:
        testgrid-dashboards: presubmits-ocp4-upi-powervs
        testgrid-tab-name: terraform-validate
    - name: pull-ocp4-upi-powervs-terraform-fmt
      always_run: true
      decorate: true
      spec:
        containers:
          - image: hashicorp/terraform
            command:
              - sh
            args:
              - -c
              - |
                set -o errexit
                terraform fmt -list -check -diff -write=false -recursive
      annotations:
        testgrid-dashboards: presubmits-ocp4-upi-powervs
        testgrid-tab-name: terraform-fmt
    - name: pull-ocp4-upi-powervs-terraform-lint
      always_run: true
      decorate: true
      spec:
        containers:
          - image: wata727/tflint
            command:
              - sh
            args:
              - -c
              - |
                set -o errexit
                tflint
                tflint ./modules/1_prepare
                tflint ./modules/4_nodes
                tflint ./modules/5_install
      annotations:
        testgrid-dashboards: presubmits-ocp4-upi-powervs
        testgrid-tab-name: terraform-lint
