presubmits:
  ocp-power-automation/ocp4-upi-powervs:
    - name: pull-ocp4-upi-powervs-terraform-validate
      always_run: true
      decorate: true
      clone_uri: "git@github.com:ocp-power-automation/ocp4-upi-powervs.git"
      spec:
        containers:
          - image: hashicorp/terraform:0.13.5
            command:
              - sh
            args:
              - -c
              - |
                set -o errexit
                terraform init
                terraform validate
      annotations:
        testgrid-dashboards: presubmits-ocp4-upi-powervs
        testgrid-tab-name: terraform-validate
