periodics:
    - name: periodic-config-docker
      cluster: k8s-ppc64le-cluster
      labels:
        preset-build-docker: "true"
      cron: 0 0 * * *
      decorate: true
      extra_refs:
        - base_ref: main
          org: ppc64le-cloud
          repo: docker-ce-build
      reporter_config:
          slack:
            channel: 'prow-job-notifications'
            report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <!subteam^S02N6DWBX0F> <{{.Status.URL}}|View logs>'
      spec:
        containers:
        - image: quay.io/powercloud/docker-ce-build@sha256:2231f00d1b1af02c018ea8f2f2ee2a890174d0bb0ce7067d128519e442776cbc
          resources:
            requests:
              cpu: "8000m"
            limits:
              cpu: "8000m"
          command:
          - /bin/bash
          args:
          - -c
          - |
            set -o errexit
            set -o nounset
            set -o pipefail
            set -o xtrace
            echo "* Start prow-info-docker *"
            chmod ug+x $PWD/upstream-master-ci/prow-info-docker.sh
            $PWD/upstream-master-ci/prow-info-docker.sh
            rc=$?
            [ $rc != 0 ] && echo "ERROR: prow-info-docker exited with code:$rc"
            exit $rc
          securityContext:
            privileged: true
          volumeMounts:
          - name: boot
            mountPath: /boot
        volumes:
        - name: boot
          hostpath:
            path: /boot/
    - name: periodic-build-dev-image-docker
      cluster: k8s-ppc64le-cluster
      labels:
        preset-build-docker: "true"
      cron: 0 3 * * *
      decorate: true
      extra_refs:
        - base_ref: main
          org: ppc64le-cloud
          repo: docker-ce-build
      reporter_config:
        slack:
          channel: 'prow-job-notifications'
          report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <!subteam^S02N6DWBX0F> <{{.Status.URL}}|View logs>'
      spec:
        containers:
        - image: quay.io/powercloud/docker-ce-build@sha256:2231f00d1b1af02c018ea8f2f2ee2a890174d0bb0ce7067d128519e442776cbc
          resources:
            requests:
              cpu: "8000m"
            limits:
              cpu: "8000m"
          command:
          - /bin/bash
          args:
          - -c
          - |
            set -o errexit
            set -o nounset
            set -o pipefail
            set -o xtrace
            echo "* Start prow-build-dev-image *"
            chmod ug+x $PWD/upstream-master-ci/prow-build-dev-image.sh
            $PWD/upstream-master-ci/prow-build-dev-image.sh
            rc=$?
            [ $rc != 0 ] && echo "ERROR: prow-build-dev-image exited with code:$rc"
            exit $rc
          securityContext:
            privileged: true
    - name: periodic-unit-test-docker
      cluster: k8s-ppc64le-cluster
      labels:
        preset-build-docker: "true"
      cron: 0 9 * * *
      decorate: true
      extra_refs:
        - base_ref: main
          org: ppc64le-cloud
          repo: docker-ce-build
      reporter_config:
        slack:
          channel: 'prow-job-notifications'
          report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <!subteam^S02N6DWBX0F> <{{.Status.URL}}|View logs>'
      spec:
        containers:
        - image: quay.io/powercloud/docker-ce-build@sha256:2231f00d1b1af02c018ea8f2f2ee2a890174d0bb0ce7067d128519e442776cbc
          resources:
            requests:
              cpu: "8000m"
            limits:
              cpu: "8000m"
          command:
          - /bin/bash
          args:
          - -c
          - |
            set -o errexit
            set -o nounset
            set -o pipefail
            set -o xtrace
            echo "* Start prow-unit-test-docker *"
            chmod ug+x $PWD/upstream-master-ci/prow-unit-test-docker.sh
            $PWD/upstream-master-ci/prow-unit-test-docker.sh
            rc=$?
            [ $rc != 0 ] && echo "ERROR: prow-unit-test-docker exited with code:$rc"
            exit $rc
          securityContext:
            privileged: true
    - name: periodic-integration-test-docker
      cluster: k8s-ppc64le-cluster
      labels:
        preset-build-docker: "true"
      cron: 0 14 * * *
      decorate: true
      decoration_config:
        timeout: 3h
      extra_refs:
        - base_ref: main
          org: ppc64le-cloud
          repo: docker-ce-build
      reporter_config:
        slack:
          channel: 'prow-job-notifications'
          report_template: 'Job {{.Spec.Job}} of type {{.Spec.Type}} ended with state {{.Status.State}}. <!subteam^S02N6DWBX0F> <{{.Status.URL}}|View logs>'
      spec:
        containers:
        - image: quay.io/powercloud/docker-ce-build@sha256:2231f00d1b1af02c018ea8f2f2ee2a890174d0bb0ce7067d128519e442776cbc
          resources:
            requests:
              cpu: "8000m"
            limits:
              cpu: "8000m"
          command:
          - /bin/bash
          args:
          - -c
          - |
            set -o errexit
            set -o nounset
            set -o pipefail
            set -o xtrace
            echo "* Start prow-integration-tests *"
            chmod ug+x $PWD/upstream-master-ci/prow-integration-tests.sh
            $PWD/upstream-master-ci/prow-integration-tests.sh
            rc=$?
            [ $rc != 0 ] && echo "ERROR: prow-integration-tests exited with code:$rc"
            exit $rc
          securityContext:
            privileged: true
