presubmits:
  trigger-prow/test-trigger:
  - name: pull-prow-trigger-test-ppc64le
    cluster: k8s-ppc64le-cluster
    always_run: true
    decorate: true
    spec:
      containers:
        - image: quay.io/powercloud/all-in-one:0.2
          command:
            - /bin/bash
          args:
            - -c
            - |
              echo "Test Prow Trigger"
    annotations:
      testgrid-dashboards: presubmits-trigger-prow-test
      testgrid-tab-name: verify-prow-trigger
