# This file contains all the required spec for service account, roles and role bindings for building/pushing the images
# built via https://github.com/vmware-tanzu/buildkit-cli-for-kubectl project.
---
apiVersion: v1
kind: Namespace
metadata:
  name: image-builder
---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: test-pods
  name: "build-img"
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: image-builder
  name: "build-img"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - list
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - create
      - get
      - delete
      - list
  - apiGroups:
      - "apps"
    resources:
      - replicasets
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: image-builder
  name: "build-img"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "build-img"
subjects:
  - kind: ServiceAccount
    name: "build-img"
    namespace: test-pods
---
apiVersion: v1
kind: Secret
metadata:
  name: build-img-secret
  namespace: test-pods
  annotations:
    kubernetes.io/service-account.name: build-img
type: kubernetes.io/service-account-token
