postsubmits:
  ocp-power-automation/ocp-power-automation.github.io:
    - name: pull-github-create-page
      labels:
        preset-ocp-ghdeploykey: "true"
      decorate: true
      always_run: true
      branches:
        - ^main$
      skip_submodules: false
      spec:
        containers:
          - image: quay.io/powercloud/mkdocs:1.0.4
            command:
              - sh
            args:
              - -c
              - |
                set -o errexit
                mkdir -p ~/.ssh
                cp /etc/ssh-key/id_rsa* ~/.ssh/
                chmod 600 ~/.ssh/id_rsa*
                eval "$(ssh-agent -s)"
                ssh-add ~/.ssh/id_rsa
                ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
                git remote add origin git@github.com:ocp-power-automation/ocp-power-automation.github.io.git
                mkdocs gh-deploy --config-file  ./mkdocs.yml --ignore-version --force
