kind: ConfigMap
apiVersion: v1
metadata:
  name: resources
  namespace: test-pods
data:
  boskos-resources.yaml: |
    resources:
      - type: "powervs-service"
        state: dirty
        names:
        - "k8s-boskos-powervs-osa21-00"
        - "k8s-boskos-powervs-osa21-01"
        - "k8s-boskos-powervs-syd04-00"
        - "k8s-boskos-powervs-syd04-01"
      - type: "vpc-service"
        state: dirty
        names:
        - "k8s-boskos-vpc-br-sao-00"
        - "k8s-boskos-vpc-ca-tor-00"
        - "k8s-boskos-vpc-jp-osa-00"
        - "k8s-boskos-vpc-eu-de-00"
