kind: ConfigMap
apiVersion: v1
metadata:
  name: resources
  namespace: test-pods
data:
  boskos-resources.yaml: |
    resources:
      - type: "powervs-service"
        state: dirty
        names:
        - "k8s-boskos-powervs-osa21-00"
        - "k8s-boskos-powervs-tok04-01"
        - "k8s-boskos-powervs-syd04-00"
        - "k8s-boskos-powervs-syd04-01"
