---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: prow
  name: deck
  annotations:
    kubernetes.io/ingress.class: public-iks-k8s-nginx
spec:
  defaultBackend:
    # specify the default backend for `ingress-gce` (https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#prow_backend)
    service:
      name: deck
      port:
        number: 80
  rules:
    - host: prow.ppc64le-cloud.cis.ibm.net
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: deck
                port:
                  number: 80
  tls:
    - hosts:
        - prow.ppc64le-cloud.cis.ibm.net
      secretName: ppc64le-cloud-cis
