---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: label-sync
  namespace: prow
spec:
  schedule: "17 * * * *"  # Every hour at 17 minutes past the hour
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        app: label-sync
    spec:
      template:
        spec:
          containers:
            - name: label-sync
              image: gcr.io/k8s-prow/label_sync:v20200724-4a9ed14895
              args:
                - --config=/etc/config/labels.yaml
                - --confirm=true
                - --only=ppc64le-cloud/test-infra,ocp-power-automation/ocp4-upi-powervs,ocp-power-automation/infra,ppc64le-cloud/kubetest2-plugins
                - --token=/etc/github/token
              volumeMounts:
                - name: oauth
                  mountPath: /etc/github
                  readOnly: true
                - name: config
                  mountPath: /etc/config
                  readOnly: true
          restartPolicy: Never
          volumes:
            - name: oauth
              secret:
                secretName: github-token
            - name: config
              configMap:
                name: label-config
