---
apiVersion: v1
kind: Service
metadata:
  name: mergeable
  namespace: prow
spec:
  selector:
    app: prow
    component: mergeable
  ports:
  - port: 80
    targetPort: 8888
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mergeable
  labels:
    app: prow
    component: mergeable
  namespace: prow
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: prow
      component: mergeable
  template:
    metadata:
      labels:
        app: prow
        component: mergeable
    spec:
      containers:
      - name: mergeable
        image: ghcr.io/ppc64le-cloud/prow-plugins:v0.1.3
        imagePullPolicy: Always
        command:
        - /mergeable
        args:
        - --github-token-path=/etc/github/token
        - --github-endpoint=http://ghproxy
        - --github-endpoint=https://api.github.com
        - --dry-run=false
        - --update-period=6h
        ports:
          - name: http
            containerPort: 8888
        volumeMounts:
        - name: hmac
          mountPath: /etc/webhook
          readOnly: true
        - name: oauth
          mountPath: /etc/github
          readOnly: true
        - name: tmp
          mountPath: /tmp
        - name: plugins
          mountPath: /etc/plugins
          readOnly: true
        resources:
          requests:
            memory: "300Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz/ready
            port: 8081
      volumes:
      - name: hmac
        secret:
          secretName: hmac-token
      - name: oauth
        secret:
          secretName: github-token
      - name: tmp
        emptyDir: {}
      - name: plugins
        configMap:
          name: plugins
