kind: ExternalSecret
metadata:
  name: external-secret-janitor
spec:
  refreshInterval: 60m
  secretStoreRef:
    name: secretstore-ibm
    kind: ClusterSecretStore
  target:
    name: ibmcloud-janitor-secret
    creationPolicy: Owner
  data:
  - secretKey: key
    remoteRef:
      key: 160fca4f-00e7-e60f-cb6b-1fd684b7766e
