apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ppc64le-cloud-tls
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secretstore-ibm
    kind: ClusterSecretStore
  target:
    name: ppc64le-cloud
    # this is how the Kind=Secret will look like
    template:
      type: kubernetes.io/tls
  data:
  - secretKey: tls.crt
    remoteRef:
      key: public_cert/82d10b13-e2dd-7f8c-7515-4346747035aa
      property: certificate
  - secretKey: tls.key
    remoteRef:
      key: public_cert/82d10b13-e2dd-7f8c-7515-4346747035aa
      property: private_key
