apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secretstore-ibm
spec:
  provider:
    ibm:
      serviceUrl: "https://654fc93a-61d6-4637-b77b-bd712d8cf5c1.us-south.secrets-manager.appdomain.cloud"
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibm-secret
            key: apiKey
