apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore-ibm
spec:
  provider:
    ibm:
      serviceUrl: "https://8839df52-56c9-4eff-a5be-9c75210f8916.us-south.secrets-manager.appdomain.cloud"
      auth:
        secretRef:
          secretApiKeySecretRef:
            name: ibm-cloud-credentials
            key: IBMCLOUD_API_KEY
            namespace: test-pods
