  periodics:
  - name: kubeflow-pipelines-component-yaml-ppc64le
    cluster: kubeflow-ppc64le-cluster
    decorate: true
    cron: "0 12 * * *"
    extra_refs:
      - base_ref: master
        org: kubeflow
        repo: pipelines
        workdir: true
    spec:
      containers:
        - image: ppc64le/python:3.7
          imagePullPolicy: Always
          command:
          - ./test/presubmit-component-yaml.sh
