presubmits:
  ppc64le-cloud/kubetest2-plugins:
    - name: pull-kubetest2-plugins-terraform-validate
      decorate: true
      run_if_changed: 'data/data'
      spec:
        containers:
          - image: hashicorp/terraform:0.12.29
            command:
              - sh
            args:
              - -c
              - |
                set -o errexit
                terraform init data/data/powervs
                terraform validate data/data/powervs
      annotations:
        testgrid-dashboards: presubmits-kubetest2-plugins
        testgrid-tab-name: terraform-validate
