periodics:
  - name: periodics-kubernetes-bazel-test-ppc64le
    cluster: k8s-ppc64le-cluster
    decorate: true
    interval: 3h
    extra_refs:
      - base_ref: master
        org: kubernetes
        repo: kubernetes
        workdir: true
      - base_ref: master
        org: kubernetes
        repo: test-infra
    spec:
      containers:
        - image: quay.io/powercloud/bazel:2.2.0
          command:
            - ../test-infra/hack/bazel.sh
          args:
            - test
            - --config=unit
            - --features=-race     # TO-DO: This need to be fixed!
            - --host_javabase=@local_jdk//:jdk
            - //...
            - --
            - -//build/...
            - -//vendor/...
  - name: periodic-kubernetes-conformance-test-ppc64le
    cluster: k8s-ppc64le-cluster
    decorate: true
    interval: 1h
    extra_refs:
      - base_ref: master
        org: ppc64le-cloud
        repo: kubetest2-plugins
        workdir: true
    spec:
      volumes:
        - name: powercloud-bot-key
          secret:
            defaultMode: 256
            secretName: bot-ssh-secret
      containers:
        - image: quay.io/powercloud/all-in-one:0.1
          command:
            - /bin/bash
          volumeMounts:
            - mountPath: /etc/secret-volume
              name: powercloud-bot-key
              readOnly: true
          envFrom:
            - secretRef:
                name: ibm-cloud-credentials
          args:
            - -c
            - |
              set -o errexit
              set -o nounset
              set -o pipefail
              set -o xtrace

              export PATH=$GOPATH/bin:$PATH
              export GO111MODULE=on

              go install ./...

              mkdir -p $HOME/.terraform.d/plugins/linux_`go env GOARCH`
              git clone https://github.com/IBM-Cloud/terraform-provider-ibm -b v1.10.0
              cd terraform-provider-ibm; go build .
              cp terraform-provider-ibm $HOME/.terraform.d/plugins/linux_`go env GOARCH`/terraform-provider-ibm_v1.10.0

              go get github.com/hashicorp/terraform-provider-null
              cp $GOPATH/bin/terraform-provider-null $HOME/.terraform.d/plugins/linux_`go env GOARCH`/

              go get sigs.k8s.io/kubetest2@latest
              go get sigs.k8s.io/kubetest2/kubetest2-tester-ginkgo@latest

              TIMESTAMP=$(date +%s)
              K8S_BUILD_VERSION=$(curl https://storage.googleapis.com/kubernetes-release-dev/ci/latest.txt)

              kubetest2 tf --powervs-dns k8s-tests \
                --powervs-dns-zone k8s.test \
                --powervs-image-name centos-8-latest \
                --powervs-region lon --powervs-zone lon06 \
                --powervs-service-id de6f50e0-7c85-4964-835c-6d767520d656 \
                --powervs-ssh-key powercloud-bot-key \
                --ssh-private-key /etc/secret-volume/ssh-privatekey \
                --build-version $K8S_BUILD_VERSION \
                --cluster-name k8s-cluster-$TIMESTAMP \
                --up --down --auto-approve \
                --powervs-memory 32 \
                --test=ginkgo -- --parallel 10 --test-package-bucket kubernetes-release-dev --test-package-dir ci --test-package-version $K8S_BUILD_VERSION --focus-regex='\[Conformance\]' --skip-regex='\[Disruptive\]|\[Serial\]'
