periodics:
  - name: periodics-kubernetes-bazel-test-ppc64le
    cluster: k8s-ppc64le-cluster
    decorate: true
    interval: 6h
    extra_refs:
      - base_ref: master
        org: kubernetes
        repo: kubernetes
        workdir: true
      - base_ref: master
        org: kubernetes
        repo: test-infra
    spec:
      containers:
        - image: quay.io/powercloud/bazel:2.2.0
          command:
            - ../test-infra/hack/bazel.sh
          args:
            - test
            - --config=unit
            - --features=-race     # TO-DO: This need to be fixed!
            - --host_javabase=@local_jdk//:jdk
            - //...
            - --
            - -//build/...
            - -//vendor/...
