periodics:
  - name: periodics-kubernetes-bazel-test-ppc64le
    cluster: k8s-ppc64le-cluster
    decorate: true
    interval: 6h
    extra_refs:
      - base_ref: master
        org: kubernetes
        repo: kubernetes
        workdir: true
      - base_ref: master
        org: kubernetes
        repo: test-infra
    spec:
      containers:
        - image: quay.io/powercloud/bazel:2.2.0
          command:
            - ../test-infra/hack/bazel.sh
          args:
            - test
            - --config=unit
            - --features=-race     # TO-DO: This need to be fixed!
            - --host_javabase=@local_jdk//:jdk
            - //...
            - --
            - -//build/...
            - -//vendor/...
  - name: periodic-kubernetes-conformance-test-ppc64le
    decorate: true
    interval: 3h
    spec:
      volumes:
        - name: powercloud-bot-key
          secret:
            defaultMode: 256
            secretName: bot-ssh-secret
      containers:
        - image: gcr.io/k8s-testimages/kubekins-e2e:v20200819-491a5ae-master
          command:
            - runner.sh
          volumeMounts:
            - mountPath: /etc/secret-volume
              name: powercloud-bot-key
              readOnly: true
          envFrom:
            - secretRef:
                name: ibm-cloud-credentials
          args:
            - "/bin/bash"
            - "-c"
            - set -o errexit;
              set -o nounset;
              set -o pipefail;
              set -o xtrace;
              wget -q -nc -O - https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip | gunzip -S .zip - > /usr/local/bin/terraform;
              chmod +x /usr/local/bin/terraform;/usr/local/bin/terraform version;
              mkdir -p $HOME/.terraform.d/plugins/linux_amd64;
              wget -q https://github.com/IBM-Cloud/terraform-provider-ibm/releases/download/v1.10.0/linux_amd64.zip;
              unzip linux_amd64.zip -d $HOME/.terraform.d/plugins/linux_amd64;
              export GO111MODULE=on;
              go get sigs.k8s.io/kubetest2@latest;
              go get sigs.k8s.io/kubetest2/kubetest2-tester-ginkgo@latest;
              GOPROXY=direct go get github.com/ppc64le-cloud/kubetest2-plugins/kubetest2-tf@latest;
              kubetest2 tf --powervs-dns k8s-tests \;
                --powervs-dns-zone k8s.test \;
                --powervs-image-name centos-8-latest \;
                --powervs-network-name k8s-test-network \;
                --powervs-region lon --powervs-zone lon06 \;
                --powervs-service-id de6f50e0-7c85-4964-835c-6d767520d656 \;
                --powervs-ssh-key powercloud-bot-key \;
                --ssh-private-key /etc/secret-volume/ssh-privatekey \;
                --build-version v1.20.0-alpha.0.635+fd74333a971e20 \;
                --cluster-name k8s-cluster-dhqkjj \;
                --up --down --auto-approve \;
                --workers-count 3 \;
                --test=ginkgo -- --parallel 30 --test-args -host=https://k8s-cluster-dhqkjj-master.k8s.test:992 --focus-regex='\[Conformance\]' --skip-regex='\[Disruptive\]|\[Serial\]';
