periodics:
  - name: periodic-capi-provider-ibmcoud-e2e-powervs
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    decoration_config:
      gcs_configuration:
        bucket: ppc64le-kubernetes
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials
    cron: "0 9,21 * * *"
    extra_refs:
      - base_ref: main
        org: kubernetes-sigs
        repo: cluster-api-provider-ibmcloud
        workdir: true
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230703-e6ae5b372a-1.27
          resources:
          limits:
           cpu: "2500m"
          requests:
           cpu: "2500m"
          env:
            - name: "E2E_FLAVOR"
              value: "powervs-md-remediation"
            - name: "BOSKOS_HOST"
              value: "boskos.test-pods.svc.cluster.local"
          command:
            - "runner.sh"
            - "./scripts/ci-e2e.sh"
          securityContext:
            privileged: true
  - name: periodic-capi-provider-ibmcoud-e2e-vpc
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
    decorate: true
    decoration_config:
      gcs_configuration:
        bucket: ppc64le-kubernetes
        path_strategy: explicit
      gcs_credentials_secret: gcs-credentials
    cron: "0 0 * * *"
    extra_refs:
      - base_ref: main
        org: kubernetes-sigs
        repo: cluster-api-provider-ibmcloud
        workdir: true
    spec:
      containers:
        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230703-e6ae5b372a-1.27
          env:
            - name: "E2E_FLAVOR"
              value: "vpc-load-balancer"
            - name: "BOSKOS_HOST"
              value: "boskos.test-pods.svc.cluster.local"
          command:
            - "runner.sh"
            - "./scripts/ci-e2e.sh"
          securityContext:
            privileged: true
