presubmits:
  ppc64le-cloud/test-infra:
  - name: pull-test-infra-yamllint
    always_run: true
    decorate: true
    spec:
      containers:
        - image: quay.io/kubermatic/yamllint:0.1
          command:
            - yamllint
            - -c
            - config/jobs/.yamllint.conf
            - config/jobs
            - config/prow/cluster
    annotations:
      testgrid-dashboards: presubmits-test-infra
      testgrid-tab-name: verify-yaml
