periodics:
  - name: periodic-containerd-runc-v2-test-powerVS
    labels:
       preset-containerd-powervs: "true"
    cluster: k8s-ppc64le-cluster
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: quay.io/powercloud/all-in-one:0.7
          command:
            - /bin/bash
            - -c
            - |
              set -o errexit
              set -o nounset
              set -o pipefail
              set -o xtrace

              # Connect to IBMCloud
              echo "" | ibmcloud login
              ibmcloud target -r eu-gb -g runtimes-dev-resource-group
              ibmcloud pi service-target crn:v1:bluemix:public:power-iaas:syd05:a/65b64c1f1c29460e8c2e4bbfbd893c2c:c3b44a6c-bc0c-4bc3-802c-b78ff68be862::

              wget https://raw.githubusercontent.com/ppc64le-cloud/docker-ce-build/main/test-containerd/instantiate_vm_and_test.sh
              chmod +x instantiate_vm_and_test.sh

              # Run test server
              mkdir ${ARTIFACTS}/runc_v2/
              bash -x ./instantiate_vm_and_test.sh --output ${ARTIFACTS}/runc_v2/ --name rdr-runtimes-containerd-runc-v2 --runc runc --runtime "io.containerd.runc.v2" --key atos-key 2>&1 | tee runc_v2.txt

              # Check results
              if [ -n "$(grep -En 'FAIL.*:' *.txt)" ]; then
                  echo "Failures found"
                  exit 1
              fi
              echo "Done without failure"
  - name: periodic-containerd-crun-v2-test-powerVS
    labels:
       preset-containerd-powervs: "true"
    cluster: k8s-ppc64le-cluster
    decorate: true
    interval: 24h
    spec:
      containers:
        - image: quay.io/powercloud/all-in-one:0.7
          command:
            - /bin/bash
            - -c
            - |
              set -o errexit
              set -o nounset
              set -o pipefail
              set -o xtrace

              # Connect to IBMCloud
              echo "" | ibmcloud login
              ibmcloud target -r eu-gb -g runtimes-dev-resource-group
              ibmcloud pi service-target crn:v1:bluemix:public:power-iaas:syd05:a/65b64c1f1c29460e8c2e4bbfbd893c2c:c3b44a6c-bc0c-4bc3-802c-b78ff68be862::

              wget https://raw.githubusercontent.com/ppc64le-cloud/docker-ce-build/main/test-containerd/instantiate_vm_and_test.sh
              chmod +x instantiate_vm_and_test.sh

              # Run test server
              mkdir ${ARTIFACTS}/crun_v2/
              bash -x ./instantiate_vm_and_test.sh --output ${ARTIFACTS}/crun_v2/ --name rdr-runtimes-containerd-crun-v2 --runc crun --runtime "io.containerd.runc.v2" --key atos-key 2>&1 | tee crun_v2.txt

              # Check results
              if [ -n "$(grep -En 'FAIL.*:' *.txt)" ]; then
                  echo "Failures found"
                  exit 1
              fi
              echo "Done without failure"
